In [2]:
import numpy as np

In [3]:
print('hello')

hello


##CREATING ARRAY FROM LIST


In [4]:
Array_1D=np.array([[1,3,4,5],[4,5,3,2]])
print(Array_1D*3)


[[ 3  9 12 15]
 [12 15  9  6]]


In [5]:
Array_2D=np.array ([[1,3,5,4,5] , [4,5,3,1,1,1,12]], dtype=object)
print(Array_2D*4)

[list([1, 3, 5, 4, 5, 1, 3, 5, 4, 5, 1, 3, 5, 4, 5, 1, 3, 5, 4, 5])
 list([4, 5, 3, 1, 1, 1, 12, 4, 5, 3, 1, 1, 1, 12, 4, 5, 3, 1, 1, 1, 12, 4, 5, 3, 1, 1, 1, 12])]


In [6]:
import time
start=time.time()
python_list=[i*2 for i in range(1000)]
print('Time for creating Python list: ',time.time()-start)

start=time.time()

np_array=np.arange(1000)*2
print('Time for creating np array: ',time.time()-start)


Time for creating Python list:  0.0001704692840576172
Time for creating np array:  0.00011134147644042969


####CREATING ARRAY FROM SCRATCH


In [12]:
zeros=np.zeros((3,4))
print('zeros array: \n',zeros)

ones=np.ones((2,3))
print('ones array: \n',ones)

full=np.full((2,),7)
print('full array: \n',full)

random=np.random.random((2,3))
print('random array: \n',random)

sequence=np.arange(0,11,2)
print('sequence array: \n',sequence)

linspace=np.linspace(0,20,15)
print('linspace array: \n',linspace)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [7 7]
random array: 
 [[0.54292759 0.86992254 0.1339641 ]
 [0.88799192 0.59711522 0.58393421]]
sequence array: 
 [ 0  2  4  6  8 10]
linspace array: 
 [ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.         11.42857143 12.85714286 14.28571429 15.71428571
 17.14285714 18.57142857 20.        ]


#            Vector,Matrix and Tensor

In [8]:
vector=np.array([1,9,2])

print('Vector is: ', vector)

matrix=np.array([[1,2,4],
                [8,4,1]])
print('matrix is: ', matrix)

Tensor=np.array([[5,6],[4,1],
                [3,3],[7,9]])
print('Tensor is: ', Tensor)


Vector is:  [1 9 2]
matrix is:  [[1 2 4]
 [8 4 1]]
Tensor is:  [[5 6]
 [4 1]
 [3 3]
 [7 9]]


# ARRAY PROPERTIES

In [9]:
Array_2D=np.array([[1,2,3],
                  [94,5,9.6]])

print('Array have',Array_2D.shape, 'shape')
print('Array have',Array_2D.ndim, 'dimension')
print('Array have',Array_2D.size, 'size')
print('Array have',Array_2D.dtype, 'data-type')


Array have (2, 3) shape
Array have 2 dimension
Array have 6 size
Array have float64 data-type


# ARRAY RESHAPING

In [10]:
aray=np.arange(16)
print('\n Arange of aray is' , aray)

reshaped=aray.reshape((8,2))
print('\n Reshape of aray is' , reshaped)

#Returns copy instead of view
flattened=reshaped.flatten()
print('\n falten of reshape is :', flattened)

#Returns view instead of copy
ravel=reshaped.ravel()
print('\n ravel of reshape is :', ravel)

transpose=reshaped.T
print('\n The transpose of reshape is', transpose)




 Arange of aray is [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 Reshape of aray is [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]

 falten of reshape is : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 ravel of reshape is : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

 The transpose of reshape is [[ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]
