# NUMPY ARRAY OPERATION

In [9]:
import numpy as np


In [79]:
arrry=np.array([1,2,3,4,5,6,7,8,9,10,])
print('slicing array',arrry[2:9:3])
print('negative_indexing',arrry[-10:-1:2])

d2_aray=np.array([[1,3,4],
                  [9,2,5],
                  [3,7,9]])
print('Specific element is' ,d2_aray[1,2])
print('Entire coloumn is' ,d2_aray[2])
print('Entire coloumn is' ,d2_aray[2])
print('Specific row is' ,d2_aray[:,2])


slicing array [3 6 9]
negative_indexing [1 3 5 7 9]
Specific element is 5
Entire coloumn is [3 7 9]
Entire coloumn is [3 7 9]
Specific row is [4 5 9]


# SORTING

In [ ]:
unsorted1=np.array([3,4,2,5,6,1,8,0,7])
print('The sorted form of unsorted1 is',np.sort(unsorted1))

axis0=np.array([[1,2,3],  #ADD COLOUMN
                [4,5,6]])
print('The axis_0 is',np.sum(axis0,axis=0))

axis1=np.array([[1,2,3],  #ADD ROW
                [4,5,6]])
print('The axis_1 is',np.sum(axis1,axis=1))


The sorted form of unsorted1 is [0 1 2 3 4 5 6 7 8]
The axis_0 is [5 7 9]
The axis_1 is [ 6 15]


# FILTERING


In [ ]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print('The even_numbers is',even_numbers)

The even_numbers is [ 2  4  6  8 10]


# FILTER WITH MASK

In [ ]:
mask = numbers > 5
print('The geater than 5 is', numbers[mask])

The geater than 5 is [ 6  7  8  9 10]


# ***Fancy indexing vs np.where()***

In [19]:
indices=[0,5,9]
print( 'The indices is', numbers[indices])

where_arr = np.where(numbers > 5) 
print(where_arr)
print('The where_arr is', numbers[where_arr])

The indices is [ 1  6 10]
(array([5, 6, 7, 8, 9]),)
The where_arr is [ 6  7  8  9 10]


In [51]:
condition_array=np.where(numbers > 5,numbers*4,False)  # if ,use,else
print('The condition_array is', condition_array)

The condition_array is [ 0  0  0  0  0 24 28 32 36 40]


# *****ADDING AND REMOVING DATA*****

In [90]:
ary1=np.array([1,2,3])
ary2=np.array([4,5,6])

                #COMBINE METHOD

combined=np.concatenate((ary1,ary2))
print('The combined is', combined)

                #REMOVE METHOD  

remove=np.delete(combined,2)
print('The remove is', remove)

                #delete method
delete=np.array([0,1,3,4,5,6,7,8,89])
deleted=np.delete(delete, 2)
print('The delete is', delete)
print('delete is', deleted) 

                #insert method



The combined is [1 2 3 4 5 6]
The remove is [1 2 4 5 6]
The delete is [ 0  1  3  4  5  6  7  8 89]
delete is [ 0  1  4  5  6  7  8 89]


# ***ARRAY COMPATIBLITY***

In [63]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,9])    
print('Compatiblity shapes',a1.shape == a2.shape)

Compatiblity shapes True


# ***********COMPATIBLITY SHAPE FALSE***********


In [ ]:
row=np.array([[1,2,3],[4,5,6]])

new_row=np.array([7,8,9])
with_row=np.vstack((row , new_row))
print('The row is', row)
print('The with_row is', with_row)


coloumn=np.array([[4],[5]])
new_coloumn=np.array([[6],[7]])
with_coloumn=np.hstack((coloumn , new_coloumn))
print('The coloumn is', coloumn)
print('The with_coloumn is', with_coloumn)


The row is [[1 2 3]
 [4 5 6]]
The with_row is [[1 2 3]
 [4 5 6]
 [7 8 9]]
The coloumn is [[4]
 [5]]
The with_coloumn is [[4 6]
 [5 7]]
