In [23]:
import numpy as np
import matplotlib.pyplot as plt

In [24]:
aray1=np.array([[1, 2, 3], [4, 5, 6],
                [7, 8, 9],])
aray2=np.random.randint(1, 10, (3, 3))
aray3=np.zeros((3, 3))



# **SAVING**

In [25]:
np.save('aray1.npy', aray1)
np.save('aray2.npy', aray2)
np.save('aray3.npy', aray3)

# **LOADING**

In [26]:
loaded_aray1 = np.load('aray1.npy')
print(loaded_aray1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
try:
    logo=np.load('numpy_logo.png')
    print(logo)
    #Display
    plt.figure(figsize=(4, 4))
    plt.subplot(1, 2, 1)
    plt.imshow(logo, cmap='gray')
    plt.title('Logo')
    plt.grid (False)
    plt.show()

     
except FileNotFoundError:
    print("File not found. Please check the file path and try again.")

File not found. Please check the file path and try again.
